<nav class="navbar navbar-default navbar-fixed-bottom">
<div class="container"> 
        <footer>
            <div> 
                <p style="font-style: italic; text-align: right; margin-right: -200px; margin-top: 10px; color: cadetblue;">
                    <strong>Forum du Groupe</strong> Fanta - Amandine - Anna - Julien - Alexandre - Pascal </p>
            </div>
        </footer>
</div>      
</nav>  


</body>
</html>
