<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Forum</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
        <link href='https://fonts.googleapis.com/css?family=Aubrey' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
        <link rel="stylesheet" media="screen" href="/forum2/css/style.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="/forum2/script.js"></script>
    </head>
    
    <body>
        <header>
            <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
            <h1 id="headerh1" >Notre Forum</h1>
            </div>
                
            </nav>

                   <div class="navbar navbar-default navbar-static">
                       <div class="container">
                           <div class="navbar-collapse collapse">
                                <ul class="nav navbar-nav">
                                    <li><a href="signup.php" class="hover">Inscription</a></li>
                                <li><a href="login.php" class="hover"> Connexion</a></li>
                                <li><a href="backoffice.php" class="hover">Back-Office</a></li>
                                <li><a href="profil.php" class="hover"> Mon profil</a></li>
                                <li><a href="logout.php" class="hover">Déconnexion</a></li>
                                </ul>
                           </div>
                        </div> 
                   </div>

        
       </header>

        <nav class="breadcrumb">
           <div class="btn-group">
                <ul>
                    <li><a href="index.php">Accueil</a></li>
                    <li><a href="#">Catégorie</a></li>
                    <li><a href="topic.php">Topic</a></li>
                </ul>
           </div>
        </nav> 
       
        
        